// Generated by CoffeeScript 1.7.1
(function() {
  Ext.define('GSW.model.Surface', {
    extend: 'GSW.model.Base',
    fields: [
      {
        name: 'imageURI',
        type: 'string',
        defaultValue: ''
      }
    ],
    hasMany: 'Zone',
    hasMany: 'ImageAnnotation',
    getImageURI: function() {
      return this.get('imageURI');
    }
  });

}).call(this);
