// Generated by CoffeeScript 1.7.1
(function() {
  Ext.define('GSW.view.transcription.ContextMenu', {
    extend: 'Ext.menu.Menu',
    constructor: function(config) {
      this.callParent(config);
      if (!(this.editor = config.editor)) {
        return Ext.Error.raise("editor not given");
      }
    },
    items: [
      {
        text: 'TEI属性情報を編集'
      }, {
        text: 'マークアップを削除'
      }, '-', {
        text: 'アノテーションを編集'
      }, {
        text: 'アノテーションを削除'
      }
    ]
  });

}).call(this);
